modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/kawaiicakes/VS2-CBC-Armor-Multiloader/issues"
license = "MIT"

[[mods]]
modId = "vscarmor"
version = "${version}"
displayName = "VS2/CBC Armor Blocks"
authors = "kawaiicakes, BlackBirdAntlion"
description = '''
Elegant armor blocks designed for use with Create: Big Cannons & Valkyrien Skies. Texture assets lovingly made by https://x.com/BlackbirdieAnt
'''
logoFile = "icon.png"

[[dependencies.vscarmor]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vscarmor]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vscarmor]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"